#include "resource.h"
#include <opencv2/opencv.hpp>
#include <objidl.h>
#include <windows.h>
#include <string>
#include <optional>
#include <iostream>
#include <gdiplus.h>
#include <psapi.h>
#include <commctrl.h>
#include <tchar.h>
#include <map>
#include <locale>
#include <codecvt>
#include <shobjidl.h>
#include <opencv2/core/cuda.hpp>
#include <opencv2/cudaarithm.hpp>
#include <opencv2/gapi/imgproc.hpp>
#include <opencv2/cudafilters.hpp>
#include <chrono>